<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <ApplicationIcon>Assets\AppLogo.ico</ApplicationIcon>
    <DefaultItemExcludes>$(DefaultItemExcludes);External\**;Tests\**</DefaultItemExcludes>
    <InformationalVersion>0.17.1+$([System.DateTime]::UtcNow.ToString("yyyyMMdd-HHmm"))</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AssetsTools.NET.Addressables" Version="3.0.2" />
    <PackageReference Include="AssetsTools.NET.Texture" Version="3.0.2" />
    <PackageReference Include="SharpSevenZip" Version="2.0.36" />
    <PackageReference Include="WPF-UI" Version="4.2.0" />
    <PackageReference Include="System.Text.Json" Version="9.0.3" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="MediaDevices" Version="1.10.0" />
    <PackageReference Include="Tinify" Version="1.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="External\merge-mansion-dumper\merge-mansion-dumper.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\ImageSplitterIcon.ico" />
    <Resource Include="Assets\AppLogo.ico" />
    <Resource Include="Assets\AppAboutLogo.jpg" />
    <Resource Include="Assets\ClaudeIcon.png" />
    <Resource Include="Assets\OnepiecefreakAvatar.png" />
    <Resource Include="Assets\SplashLogo.png" />
  </ItemGroup>

</Project>
