<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <ApplicationIcon>Assets\AppLogo.ico</ApplicationIcon>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AssetsTools.NET.Addressables" Version="3.0.2" />
    <PackageReference Include="AssetsTools.NET.Texture" Version="3.0.2" />
    <PackageReference Include="WPF-UI" Version="4.2.0" />
    <PackageReference Include="System.Text.Json" Version="9.0.3" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="Tinify" Version="1.9.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\ImageSplitterIcon.ico" />
    <Resource Include="Assets\AppLogo.ico" />
    <Resource Include="Assets\AppAboutLogo.jpg" />
    <Resource Include="Assets\ClaudeIcon.png" />
    <Resource Include="Assets\SplashLogo.png" />
  </ItemGroup>

</Project>
