using System;
using System.Collections.Generic;
using System.Linq;
using MergeMansionWikiTools.Models;
using MergeMansionWikiTools.Services;
using Xunit;

namespace MergeMansionWikiTools.Tests;

public class DialogueArchiveServiceTests
{
    private static readonly Dictionary<string, List<ArchivedLine>> NoExistingArchive = new();

    private static DialogueScene SceneWith(string id, string text) => new()
    {
        Id = "S", Area = "Attic",
        Lines = { new DialogueLineInfo { Id = id, Text = text, Speaker = "Maddie" } },
    };

    [Fact]
    public void Rewritten_line_is_archived_with_the_version_it_ended_in()
    {
        var existing = new Dictionary<string, string> { ["S_01"] = "I've got a cherry pie cooling." };

        var diff = DialogueArchiveService.Compute(NoExistingArchive, existing,
            new List<DialogueScene> { SceneWith("S_01", "I'm going to bake a cake for your new friend.") },
            "26.07.01");

        var entry = Assert.Single(diff.Added);
        Assert.Equal("S_01", entry.LineId);
        Assert.Equal("I've got a cherry pie cooling.", entry.Text);
        Assert.Equal("26.07.01", entry.Until);
        // Also reflected in the merged result that's handed to RenderArchive.
        Assert.Equal("I've got a cherry pie cooling.", diff.FinalArchive["S_01"].Single().Text);
    }

    [Fact]
    public void Cosmetic_fix_is_not_archived()
    {
        var existing = new Dictionary<string, string> { ["S_01"] = "Hello there!" };

        var diff = DialogueArchiveService.Compute(NoExistingArchive, existing,
            new List<DialogueScene> { SceneWith("S_01", "Hello there...") }, "26.07.01");

        Assert.Empty(diff.Added);
    }

    [Fact]
    public void Unchanged_line_produces_no_entry()
    {
        var existing = new Dictionary<string, string> { ["S_01"] = "Same." };

        var diff = DialogueArchiveService.Compute(NoExistingArchive, existing,
            new List<DialogueScene> { SceneWith("S_01", "Same.") }, "26.07.01");

        Assert.Empty(diff.Added);
    }

    [Fact]
    public void Merge_keeps_archived_lines_that_are_no_longer_in_the_dump()
    {
        // S_02 was archived earlier but its scene is gone entirely from the current dump —
        // no live text for it either. Its history must still survive the merge.
        var existingArchive = new Dictionary<string, List<ArchivedLine>>
        {
            ["S_02"] = new() { new ArchivedLine("S_02", "Long gone wording", "26.01.01") },
        };

        var diff = DialogueArchiveService.Compute(existingArchive,
            new Dictionary<string, string>(), new List<DialogueScene>(), "26.07.01");

        Assert.Equal("Long gone wording", diff.FinalArchive["S_02"].Single().Text);
        Assert.Contains(diff.Carried, c => c.LineId == "S_02" && c.Text == "Long gone wording");
    }

    [Fact]
    public void Archive_round_trips_through_lua()
    {
        var lua = DialogueArchiveService.RenderArchive(new Dictionary<string, List<ArchivedLine>>
        {
            ["S_01"] = new() { new ArchivedLine("S_01", "Old wording", "26.02.01") },
        });

        var parsed = DialogueArchiveService.ParseArchive(lua);

        Assert.Equal("Old wording", parsed["S_01"].Single().Text);
        Assert.Equal("26.02.01", parsed["S_01"].Single().Until);
    }

    [Fact]
    public void Carriage_return_in_archived_text_is_escaped_and_round_trips()
    {
        // nezaviresny navrat vozika uvnitr uvozovkovaneho Lua retezce by rozbil parsovani a shodil
        // cely modul - musi se escapovat stejne jako "\n"
        var lua = DialogueArchiveService.RenderArchive(new Dictionary<string, List<ArchivedLine>>
        {
            ["S_01"] = new() { new ArchivedLine("S_01", "Line one\rLine two", "26.02.01") },
        });

        Assert.Contains("Line one\\rLine two", lua);   // escapovane v generovanem zdroji, ne syrove
        var parsed = DialogueArchiveService.ParseArchive(lua);
        Assert.Equal("Line one\rLine two", parsed["S_01"].Single().Text);
    }

    [Fact]
    public void Missing_archive_module_returns_empty_dictionary_without_throwing()
    {
        // First-ever run — no archive page exists on the wiki yet.
        Assert.Empty(DialogueArchiveService.ParseArchive(null));
        Assert.Empty(DialogueArchiveService.ParseArchive(""));
        Assert.Empty(DialogueArchiveService.ParseArchive("   \n  "));
    }

    [Fact]
    public void Legitimately_empty_archive_table_returns_empty_dictionary_without_throwing()
    {
        var lua = "-- Previous wordings of dialogue lines that were rewritten in a later game version.\n"
            + "-- Generated by MergeMansionWikiTools; do not edit by hand.\nreturn {\n}\n";

        Assert.Empty(DialogueArchiveService.ParseArchive(lua));
    }

    [Fact]
    public void Corrupted_module_throws_instead_of_silently_dropping_entries()
    {
        // Shape says one entry ("S_01" bracket is there), but the "until" field lost its quotes —
        // as if something reformatted the module — so the item body can't actually be parsed.
        var lua = "return {\n  [\"S_01\"] = { { text = \"Old wording\", until = 26.02.01 }, },\n}\n";

        Assert.Throws<InvalidOperationException>(() => DialogueArchiveService.ParseArchive(lua));
    }
}
