<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MergeMansionWikiTools.Dumper</RootNamespace>
    <AssemblyName>MMWT.Dumper</AssemblyName>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\External\merge-mansion-api\merge-mansion-api.csproj" />
  </ItemGroup>
</Project>
